### ISSUE TITLE
loading function defaults 

### ISSUE THREAD

**Issue by aghaynes** [adam-gruer/runcomments#1]
Hi! Interesting looking package. Just started to try it out...

A similar thing that would be really handy for developing functions would be a way to create objects that a function needs to work based on the (selected part of a) function definition

E.g.

`
x <- function(
x1 = "foo",
x2 = "bar", 
...
)
`
create objects x1 and x2 with values "foo" and "bar" in this case...

It's almost an identical problem to which I've never found a particularly satisfying solution...

**Comment by andycraig** [comment]
Hi @aghaynes, I think the [assign_defaults_addin](https://github.com/jennybc/jadd#assign_defaults_addin) would do what you want?

**Comment by aghaynes** [comment]
That does indeed sound exactly like what I meant! Thanks!
